/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'badges' : IDL.Vec(IDL.Text),
  'totalCoins' : IDL.Nat,
  'lastActiveDate' : IDL.Text,
  'level' : IDL.Nat,
  'bestStreak' : IDL.Nat,
  'currentStreak' : IDL.Nat,
});
export const TaskDefinition = IDL.Record({
  'id' : IDL.Nat,
  'duration' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'coinReward' : IDL.Nat,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCustomCategory' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createTaskDefinition' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
      [IDL.Nat],
      [],
    ),
  'deleteTaskDefinition' : IDL.Func([IDL.Nat], [], []),
  'getAllTimeStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalCoins' : IDL.Nat,
          'bestStreak' : IDL.Nat,
          'currentLevel' : IDL.Nat,
          'totalTasksCompleted' : IDL.Nat,
          'currentStreak' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompletedTasksForDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Nat)],
      ['query'],
    ),
  'getCustomCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getMonthlyStats' : IDL.Func(
      [IDL.Vec(IDL.Text)],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Nat))],
      ['query'],
    ),
  'getRandomQuote' : IDL.Func([], [IDL.Text], ['query']),
  'getTaskDefinitions' : IDL.Func([], [IDL.Vec(TaskDefinition)], ['query']),
  'getTodayTasks' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(TaskDefinition, IDL.Bool))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWeeklyStats' : IDL.Func(
      [IDL.Vec(IDL.Text)],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Nat))],
      ['query'],
    ),
  'initialize' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markTaskComplete' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'removeCustomCategory' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateTaskDefinition' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat), IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'badges' : IDL.Vec(IDL.Text),
    'totalCoins' : IDL.Nat,
    'lastActiveDate' : IDL.Text,
    'level' : IDL.Nat,
    'bestStreak' : IDL.Nat,
    'currentStreak' : IDL.Nat,
  });
  const TaskDefinition = IDL.Record({
    'id' : IDL.Nat,
    'duration' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'coinReward' : IDL.Nat,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCustomCategory' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createTaskDefinition' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
        [IDL.Nat],
        [],
      ),
    'deleteTaskDefinition' : IDL.Func([IDL.Nat], [], []),
    'getAllTimeStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalCoins' : IDL.Nat,
            'bestStreak' : IDL.Nat,
            'currentLevel' : IDL.Nat,
            'totalTasksCompleted' : IDL.Nat,
            'currentStreak' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompletedTasksForDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Nat)],
        ['query'],
      ),
    'getCustomCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getMonthlyStats' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Nat))],
        ['query'],
      ),
    'getRandomQuote' : IDL.Func([], [IDL.Text], ['query']),
    'getTaskDefinitions' : IDL.Func([], [IDL.Vec(TaskDefinition)], ['query']),
    'getTodayTasks' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(TaskDefinition, IDL.Bool))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWeeklyStats' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Nat))],
        ['query'],
      ),
    'initialize' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markTaskComplete' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'removeCustomCategory' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateTaskDefinition' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat), IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };