/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface TaskDefinition {
  'id' : bigint,
  'duration' : [] | [bigint],
  'name' : string,
  'coinReward' : bigint,
  'category' : string,
}
export interface UserProfile {
  'badges' : Array<string>,
  'totalCoins' : bigint,
  'lastActiveDate' : string,
  'level' : bigint,
  'bestStreak' : bigint,
  'currentStreak' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCustomCategory' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createTaskDefinition' : ActorMethod<[string, string, [] | [bigint]], bigint>,
  'deleteTaskDefinition' : ActorMethod<[bigint], undefined>,
  'getAllTimeStats' : ActorMethod<
    [],
    {
      'totalCoins' : bigint,
      'bestStreak' : bigint,
      'currentLevel' : bigint,
      'totalTasksCompleted' : bigint,
      'currentStreak' : bigint,
    }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompletedTasksForDate' : ActorMethod<[string], Array<bigint>>,
  'getCustomCategories' : ActorMethod<[], Array<string>>,
  'getMonthlyStats' : ActorMethod<
    [Array<string>],
    Array<[string, bigint, bigint]>
  >,
  'getRandomQuote' : ActorMethod<[], string>,
  'getTaskDefinitions' : ActorMethod<[], Array<TaskDefinition>>,
  'getTodayTasks' : ActorMethod<[string], Array<[TaskDefinition, boolean]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWeeklyStats' : ActorMethod<
    [Array<string>],
    Array<[string, bigint, bigint]>
  >,
  'initialize' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markTaskComplete' : ActorMethod<[bigint, string], undefined>,
  'removeCustomCategory' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateTaskDefinition' : ActorMethod<
    [bigint, string, string, [] | [bigint], bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];